### PR TITLE
Add manual trigger for github action

### PR DESCRIPTION
**Pull request by k-lpmg**
### Feature
Add manual trigger button for testing

Screen Shot 2022-01-27 at 7 12 23 PM

### CODE REVIEW

**Comment by techinpark** [comment]
@k-lpmg Thank you for your contribution. Why did you close it?

**Comment by k-lpmg** [comment]
Hi @techinpark 

https://github.com/techinpark/appstore-status-bot/blob/3cadf95023d72f56df345516407c4aeadad18e7d/Sources/check_status.js#L33

The above code was executed, the following error occurred in the github action.

So I looked into the cause and tried to post a PR again, but do you know what kind of issue it is?

Screen Shot 2022-01-28 at 9 45 38 AM

**Comment by k-lpmg** [comment]
I tried again on the master branch and it worked fine.
It seems to be an issue that occurred while changing the code because there was an issue with the initial setup.

https://github.com/rogerluan/app-store-connect-notifier/blob/d93b8f2f9c8a1a08eb92aac5fe53835419a27e3b/src/fetch_app_status.rb#L57-L73

As an additional question, https://github.com/rogerluan/app-store-connect-notifier uses `get_latest_app_store_version` in `get_version_info(app)`, but in the repo, is there a reason to put a logic branch using codes such as `get_live_app_store_version`, `get_edit_app_store_version`, `get_app_store_versions`?

The reason for asking this question was the version in the `PENDING_DEVELOPER_RELEASE` state, and `get_app_state(app)` returned the contents of the previous version uploaded to the store.

**Comment by techinpark** [comment]
> The reason for asking this question was the version in the PENDING_DEVELOPER_RELEASE state, and get_app_state returned the contents of the previous version uploaded to the store.

@k-lpmg correct! know the problem and need to resolve it.

**Comment by k-lpmg** [comment]
Can't `get_latest_app_store_version` solve it right now? I wonder if there will be other side effects.

I'd be happy if this issue was resolved quickly!

**Comment by techinpark** [comment]
@k-lpmg I will resolve this issue as soon thank you.

**Review by techinpark — APPROVED** [review]

**Pull request merged**
